[project]
name = "merlin"
version = "0.2.1"
description = "A granular home automation platform."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.9.0",
    "aiomqtt>=2.5.1",
    "aiosqlite>=0.20.0",
    "geopy>=2.4.1",
    "pydantic>=2.5.0",
    "pysqlite3>=0.5.2",
]

[project.scripts]
merlin = "merlin.main:main"

[build-system]
requires = ["hatchling"]
build-backend="hatchling.build"